### ISSUE TITLE
Diagnostics: RTSP server disabled -  how can I enable it?

### ISSUE THREAD

**Issue by mongoq** [rzeldent/esp32cam-rtsp#100]
I can't seem to be able to enable the RTSP server. It shows up in the configuration page as disabled. Connecting with VLC won't work, neither does FFmpeg. What am I doing wrong?

**Comment by rzeldent** [comment]
Take. a look at the output. Probably wrong board/camera error

**Comment by mongoq** [comment]
Ah, I fixed it. You need to connect it to an access point, then you can use "ffplay rtsp://172.20.10.2:554/mjpeg/1". The website will show the number of RTSP sessions.

**Comment by rzeldent** [comment]
Great! Enjoy
