### ISSUE TITLE
Authentication impossible

### ISSUE THREAD

**Issue by kapabel** [rzeldent/esp32cam-rtsp#101]
Hello,
I am sure I am using it wrong but I cant get the authentication to work.
When setting up the device I define a AP password.

Later on when I want to change the settings it asks me for a username and password. I have tried all combinations but I can't get through. I have reflashed my ESP32CAM twice to make sure it wasn't a typo.

So whats the username and password to change settings? Is it the AP password I have defined on first setup or something completely different?

Many thanks!
Bernhard

**Comment by rzeldent** [comment]
Hi Bernhard,

It is in the manual.
![image](https://github.com/rzeldent/esp32cam-rtsp/assets/7620231/b4e5a5ec-7d63-4b83-a2d9-0c353edc73eb)

So admin and the AP Password

**Comment by kapabel** [comment]
Ha! There it was. Many thanks!

**Comment by rzeldent** [comment]
👍
