### ISSUE TITLE
How to `pio run -t upload` only on one particular board?

### ISSUE THREAD

**Issue by theschles** [rzeldent/esp32cam-rtsp#111]
Hi there,

I'm uploading via `pio run -t upload`.  That starts with the AI Thinker...and then tries to upload the next board on the list...and then the next...etc.

How do I tell it to _just_ do the AI Thinker, for instance?

**Comment by rzeldent** [comment]
Hi theschles,

This can be done by uncommenting the default_envs in the platformio.ini file for your board type...

Without modifications you can use the -e (--environment) option: https://docs.platformio.org/en/latest/core/userguide/cmd_run.html#options
