### ISSUE TITLE
Webserver very slow to respond after ~6 hours

### ISSUE THREAD

**Issue by piratos** [rzeldent/esp32cam-rtsp#121]
I am running a couple of esp32 over a 10000mah powerbanks.
I noticed the board does not handle well multiple clients so I wrote a backend server that connects once to the boards and handle recording, streaming and some other features.

my issue is that the webserver  of the esp32 becomes terribly slow after a couple of hours. the rtsp works fine tho.
I am only using the webserver to catch the board/camera details (would be cool to get this is json too, I may be able to contribute if you want) and status and the snapshot service to create a thumbnail.

I am  doubting the power banks but I think I saw the same behavior on usb power and the rtsp is fine as i mentionned.

Any idea how to troubleshoot this? thanks

Great project by the way thank you

Appendix: Board details of one with the issue
```
Board type: esp32cam_espressif_esp32s3_eye
SDK Version: v4.4.6-dirty
CPU model: ESP32-S3 rev. 0
CPU speed: 240 Mhz
CPU cores: 2
RAM size: 304.85 KB
PSRAM size: 8 MB (QSPI)
Flash size:16 MB
Diagnostics
Uptime: 06:33:31
RTSP sessions: 1
Free heap: 207.29 KB
Max free block: 191.99 KB
```

Note: it is not `esp32cam_espressif_esp32s3_eye` I just modified that board pins to match mine ([random aliexpress](aliexpress.com/item/1005006099376239.html))

**Comment by rzeldent** [comment]
Hi Sayf,

Maybe some memory leak after running for a long time? If you reboot the devices are they responsive again or is it the heat?

**Comment by piratos** [comment]
memory values seems stable from first reboot to when sever starts to slow down
I think it is indeed the heat as the temporarily plastic covering does not allow for air circulation around the chip. I ll close this issue as I looked to the code and I dont think it is sth to do with it. Thanks
