### ISSUE TITLE
xiao_esp32s3_sense cannot use rtsp stream

### ISSUE THREAD

**Issue by uecken** [rzeldent/esp32cam-rtsp#136]
I changed below in platform.ini 
default_envs = esp32cam_seeed_xiao_esp32s3_sense
then upload , wifi connected.
Web Jpeg stream can be done, but RTSP stream cannot be successed.

![image](https://github.com/user-attachments/assets/40290dac-919f-41f6-9d41-9f0132625c97)
![image](https://github.com/user-attachments/assets/0d197e8f-a5c7-4b72-8406-836adee3e1cd)

![image](https://github.com/user-attachments/assets/240a7afc-701c-4331-b897-6e49b553e85b)
![image](https://github.com/user-attachments/assets/dc483462-da3e-4021-8c65-5adc76678dc2)

I checked the RTSP port, then the port is not opened.
/mnt/c/Users/User$ nmap 192.168.4.1
Starting Nmap 7.80 ( https://nmap.org ) at 2024-08-14 15:28 JST
Nmap scan report for 192.168.4.1
Host is up (0.019s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE
80/tcp open  http

I tried the main branch and develop branch, but same issue happend.

**Comment by rzeldent** [comment]
Have you tried configuring to connect to an access point?

**Comment by uecken** [comment]
How can I use Wifi station mode?
The SSID/PW setting can be shown in web GUI, but cannot ues properly.
![image](https://github.com/user-attachments/assets/3c814884-92d5-4cf8-890b-13748133f628)

I dont't know much about IotWebConf.


----------------------------

I tried again, then esp32 seems to try to connect to AP, but cannot connect. 


Reconnecting to COM16 --- forcing DTR inactive
--- forcing RTS inactive

Please build project in debug configuration to get more details about an exception.
See https://docs.platformio.org/page/projectconf/build_configurations.html


--- Logging an output to C:\gdrive\dev2024\esp32cam-rtsp\logs\device-monitor-240815-102517.log   
         Connected!
10:25:43.351 > State changing from: 2 to 3
10:25:43.375 > E (35831) wifi_init_default: netstack cb reg failed with 12308
10:25:43.375 > Connecting to [HUAWEIp10] (password is hidden)
10:25:43.375 > WiFi timeout (ms): 30000
10:25:43.401 > State changed from: 2 to 3
10:26:13.375 > Giving up.
10:26:13.380 > State changing from: 3 to 2
10:26:13.399 > Setting up AP: ESP32CAM-RTSP
10:26:13.400 > Use password: <hidden>
10:26:13.784 > AP IP address: 192.168.4.1
10:26:13.788 > AP timeout (ms): 30000
10:26:13.788 > State changed from: 3 to 2


----------------------------------

I forgotted put antenna. After put antenna., esp

--- Logging an output to C:\gdrive\dev2024\esp32cam-rtsp\logs\device-monitor-240815-102847.log
         Connected!
10:29:15.760 > State changing from: 2 to 3
10:29:15.769 > Connecting to [HUAWEIp10] (password is hidden)
10:29:15.771 > WiFi timeout (ms): 30000
10:29:15.795 > State changed from: 2 to 3
10:29:36.390 > WiFi connected
10:29:36.394 > IP address: 192.168.168.76
10:29:36.394 > State changing from: 3 to 4
10:29:39.495 > Active mDNS services: 0 
10:29:39.497 > Accepting connection
10:29:39.504 > State changed from: 3 to 4

**Comment by uecken** [comment]
Finally, RTSP stream connected. Thank you!!!
![image](https://github.com/user-attachments/assets/ae01a4fa-76f1-44cc-a222-bbc583da608c)

**Comment by rzeldent** [comment]
You're welcome! Nice to hear issue is resolved
