### ISSUE TITLE
How to use more than 1 camera

### ISSUE THREAD

**Issue by SergeKlutchenko** [rzeldent/esp32cam-rtsp#138]
Hello,
Thanks for your job.

After using pio pkg update

compilation give:
esp32cam_ai_thinker  SUCCESS   00:04:53.638
===================================== 1 succeeded in 00:04:53.638 =====================================

the purpose is to use Home Assistant.
I need more than one camera 
How to manage that  and how to manage the network

Second question: 
how to fill Wifi SSID and Pwd ? My home network ? 
Thanks
Serge.

**Comment by rzeldent** [comment]
Hi Serge,

Take a look aty the manual: https://github.com/rzeldent/esp32-smartdisplay-demo/actions/runs/9828688543

Yes, you'll have to provide a new password (for access to the cam) and your Wifi credentials!
Then you should be able to access the cam from your network....
