### ISSUE TITLE
Simplest way...

### ISSUE THREAD

**Issue by SergeKlutchenko** [rzeldent/esp32cam-rtsp#139]
I assume you have Visual studio Code with platformio installed.
1- download the esp32cam-rtsp folder by clicking on code.
2- In platformio do "import a project"
3- go to the imported folder.
4- import project
5- In the platformio.ini file, uncheck your board and save
For example:
      [platformio]
      default_envs = esp32cam_ai_thinker
platformio click build if ok click upload
It worked fine for me.

**Comment by SergeKlutchenko** [comment]
but i got this 
Failed to initialize the camera!
Result: 261 (ESP_ERR_NOT_FOUND)
Please check hardware or correct the camera settings and restart.

**Comment by Moko0815** [comment]
Processing esp32cam_ai_thinker (board: esp32cam_ai_thinker; platform: espressif32; framework: arduino)
UnknownBoard: Unknown board ID 'esp32cam_ai_thinker'

**Comment by rzeldent** [comment]
Have you cloned the project with submodules?
