### ISSUE TITLE
Stream not working in HA

### ISSUE THREAD

**Issue by smartroad** [rzeldent/esp32cam-rtsp#20]
Hi!

I have been able to get this installed on a generic ESP32CAM board and get it logged into HA, showing a picture (using "Generic Camera" integration). Works fine to show a (slowly updating) picture but when I click and it switches to showing the stream it shows an error. It flickers with the player and has occasionally the error: "Error with media stream contents". VLC shows the stream perfectly though :)

Tried with Firefox and Edge

**Comment by rzeldent** [comment]
Hi SmartRoad,

What is HA?

Rene

**Comment by crivera8602** [comment]
I believe HA means Home assistant

**Comment by rzeldent** [comment]
Hi smartroad / crivera,

Thanks for clarifying HA! Home Assistant!

I looked at the documentation of HA https://www.home-assistant.io/integrations/generic/ and was wondering if the complete RTSP URL was entered. If this is the case, is there some error message or logging?

Thanks and kind regards,

Rene

**Comment by rzeldent** [comment]
Are there any warnings or logging? Did you use the DNS name or the IP address?

**Comment by crivera8602** [comment]
it integrates fine on my end  <a href="https://ibb.co/1X0bQM0"><img src="https://i.ibb.co/R6g7bNg/Screenshot-from-2022-11-04-01-27-58.png" alt="Screenshot-from-2022-11-04-01-27-58" border="0"></a>

only thing i noticed was the image disconnecting randomly 

https://user-images.githubusercontent.com/63074950/199900343-4c2dc388-aedf-4de9-bc3b-cd785b996cae.mp4

**Comment by rzeldent** [comment]
HI Crivera,

Thanks for investigating this. I saw the glitch in the stream. Maybe the resolution is too high or the framerate too fast (or wifi connectivity?) so sometimes frames are skipped. Is this maybe the case?

Regards,

Rene

**Comment by rzeldent** [comment]
It looks like it is working in Home Assistent. So will close this issue.

**Comment by bjoernmayer** [comment]
@smartroad did you get it working? I am facing the same issue
