### ISSUE TITLE
Trouble compiling in VSCode 

### ISSUE THREAD

**Issue by KingBain** [rzeldent/esp32cam-rtsp#34]
![image](https://user-images.githubusercontent.com/367922/211941281-df798ef9-ad9c-48ab-96da-e7852b9d5d02.png)

Compiling .pio\build\esp32cam\src\main.cpp.o
In file included from src\main.cpp:9:0:
include/frame_size.h:18:17: error: 'FRAMESIZE_240X240' was not declared in this scope
     {"240x240", FRAMESIZE_240X240},
                 ^
include/frame_size.h:21:24: error: 'FRAMESIZE_HVGA' was not declared in this scope
     {"HVGA (480x320)", FRAMESIZE_HVGA},
                        ^
include/frame_size.h:25:23: error: 'FRAMESIZE_HD' was not declared in this scope
     {"HD (1280x720)", FRAMESIZE_HD},
                       ^
src\main.cpp: In function 'void stream_text_file_gzip(const unsigned char*, size_t, const char*)':
src\main.cpp:55:73: error: no matching function for call to 'WebServer::sendContent(const char*, size_t&)'
   web_server.sendContent(reinterpret_cast<const char *>(content), length);
                                                                         ^
In file included from .pio\libdeps\esp32cam\IotWebConf\src/IotWebConf.h:25:0,
                 from src\main.cpp:4:
C:\Users\Bain\.platformio\packages\framework-arduinoespressif32\libraries\WebServer\src/WebServer.h:130:8: note: candidate: void WebServer::sendContent(const String&)
   void sendContent(const String& content);
        ^
C:\Users\Bain\.platformio\packages\framework-arduinoespressif32\libraries\WebServer\src/WebServer.h:130:8: note:   candidate expects 1 argument, 2 provided
src\main.cpp: In function 'void handle_root()':
src\main.cpp:80:25: error: 'class EspClass' has no member named 'getChipModel'

**Comment by KingBain** [comment]
![image](https://user-images.githubusercontent.com/367922/211941997-f62e9c8e-be79-4074-b322-ec5e28949cf3.png)



looks like updating modules in PIO fixed the issue.

**Comment by rzeldent** [comment]
Hi John,

Thanks for sharing your experience and resolution; this might help others having the same issue!

Kind  regards,

Rene
