### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by doudz** [rzeldent/esp32cam-rtsp#38]
Hi !
It works well but it would be cool to have additionnal controls :

vertical_flip
horizontal_mirror
contrast
brightness
saturation

OTA update ;)

**Comment by rzeldent** [comment]
Hi doudz,

These image setting could be implemented, something to look into.
OTA should be present and working. You need to set the password in the settings.h file.

Kind regards,

Rene

**Comment by rzeldent** [comment]
Hi Doudz,

These have been implemented. See https://github.com/rzeldent/esp32cam-rtsp/tree/feature/update_config
Let me know if these are working for you.

Kind regards

**Comment by rzeldent** [comment]
Fixed

**Comment by doudz** [comment]
many thanks !
