### ISSUE TITLE
Static IP ?

### ISSUE THREAD

**Issue by tomtdl** [rzeldent/esp32cam-rtsp#42]
Is is possible to configure this for a static IP?  Maybe in settings page or config file?

**Comment by rzeldent** [comment]
Hi tom,

Unfortunately this is currently not possible. The library (prampec/IotWebConf) used does not offer such a possibility.
You could adapt the code youself to put in you static ip.
However, what you can do is to add a DHCP reservation on your router so it will always get the same IP address.
