### ISSUE TITLE
Failing to initialize.... #2

### ISSUE THREAD

**Issue by WSDsuperace** [rzeldent/esp32cam-rtsp#5]
Hi,
Your project looks exactly like something I really need. But... I can not get my camera to init.

Same board as reported in Failing to initialize.... #1 and I just can not get it to work. I know the PCB is good, it is working with arduino sketches.
![noinit](https://user-images.githubusercontent.com/62682123/189592447-10761b48-e222-4e40-8256-bd90f715575a.jpg)

Any ideas?

**Comment by rzeldent** [comment]
Have you checked if you're using the same IO settings as the sketch that did work?
You could try to set  the framebuffers to 1 instead of 2. You can change this in the file include/camera_config.h for AI_Thinker.
  config.fb_count = 1;

This because maybe you do not have PSRAM and saw some code in an arduino sketch:

if(psramFound()){
    config.frame_size = FRAMESIZE_UXGA;
    config.jpeg_quality = 10;
    config.fb_count = 2;
  } else {
    config.frame_size = FRAMESIZE_SVGA;
    config.jpeg_quality = 12;
    config.fb_count = 1;
  }

If you set lower resolutions, do you get an image? 

Also make sure you have a good power supply....

**Comment by rzeldent** [comment]
Made selection of PSRam automatic and fb_count configurable.
Also added two new boards; wrover and m5 stack.

Any progress on your side?

**Comment by WSDsuperace** [comment]
Brilliant!!!!!
I do not know what magic you pulled but now my boards are happy and have PSRAM. Your suggestions to change buffer to 1 did not make any difference and the IF PSRAM always retured False.  But your new build totally works!

Thank you soooooo soooo much.

On a different note, maybe you should add in the documentation (unless it is already there and I have missed it) that the only way to totally reset saved passwords is to do an erase of the flash. Build and Download does not clear previously saved passwords, at least not for me so I nuked it with
esptool.py --chip esp32 --port /dev/ttyUSB0 erase_flash 
and all was well :)
Again thank you for your help.

**Comment by rzeldent** [comment]
Hi WSDsuperace,

The magic I pulled is to check if the boards do have PSRAM. If not, DRAM is used. You can check this in the HTML status screen where the frame buffer is located. So, maybe you have a board without PSRAM?
The suggestion to erase the flash after a change in the config is a good one. I added it to the main page. Also I'll increase the configuration version so this will no longer happen.

Enjoy!

**Comment by WSDsuperace** [comment]
All my boards have PSRAM, works perfectly with Micropython but just too slow fps. With the old code I never got the camera to init and something crashed on the way, regardless where the frame buffer was allocated. So thank your for your magic.

Do you want more feature suggestions? If yes, how? Open them as an Issue? What do you suggest?
