### ISSUE TITLE
Выложите пожалуйста .bin файл

### ISSUE THREAD

**Issue by kkwestt** [rzeldent/esp32cam-rtsp#50]
Please post the .bin file for standard cameras that are listed. only 5 pieces. 
I can't build the firmware. 
But i know how to run: esptool.py write_flash camera_rtsp.bin

**Comment by rzeldent** [comment]
Hi kkwestt,

I made a release with the binary file. You can find it at: https://github.com/rzeldent/esp32cam-rtsp/releases/tag/1.0.4
Here the firmware.bin is the firmware file you're looking for...

Enjoy!

Rene
