### ISSUE TITLE
WEB does not start. Module rebooting

### ISSUE THREAD

**Issue by ivanshateev** [rzeldent/esp32cam-rtsp#56]
At the first inclusion, there was a web form with parameters. I entered the name of the wifi network with a password and changed the mode to ESP32CAM. After reloading the web form does not open and is not connected to the point. It feels like something is incorrectly stored in the EEROM

Connection to AP.
[  7218][V][WiFiGeneric.cpp:407] _arduino_event_cb(): AP Station Connected: MAC: 80:e6:50:17:69:58, AID: 1
[  7219][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 12 - AP_STACONNECTED
[  7247][V][WiFiGeneric.cpp:421] _arduino_event_cb(): AP Station IP Assigned:192.168.4.2
[  7248][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 14 - AP_STAIPASSIGNED
[  7395][V][WebServer.cpp:296] handleClient(): New client: client.localIP()=192.168.4.1
[  7398][V][Parsing.cpp:122] _parseRequest(): method: GET url: /connecttest.txt search: 
[  7400][V][Parsing.cpp:226] _parseRequest(): headerName: Cache-Control
[  7406][V][Parsing.cpp:227] _parseRequest(): headerValue: no-cache
[  7412][V][Parsing.cpp:226] _parseRequest(): headerName: Connection
[  7418][V][Parsing.cpp:227] _parseRequest(): headerValue: Close
[  7424][V][Parsing.cpp:226] _parseRequest(): headerName: Pragma
[  7429][V][Parsing.cpp:227] _parseRequest(): headerValue: no-cache
[  7436][V][Parsing.cpp:226] _parseRequest(): headerName: User-Agent
[  7441][V][Parsing.cpp:227] _parseRequest(): headerValue: Microsoft NCSI
[  7448][V][Parsing.cpp:226] _parseRequest(): headerName: Host
[  7454][V][Parsing.cpp:227] _parseRequest(): headerValue: www.msftconnecttest.com
[  7461][V][Parsing.cpp:254] _parseArguments(): args: 
[  7466][V][Parsing.cpp:237] _parseRequest(): Request: /connecttest.txt
[  7472][V][Parsing.cpp:238] _parseRequest():  Arguments: 
[  7477][E][WebServer.cpp:649] _handleRequest(): request handler not found
Request for www.msftconnecttest.com redirected to 192.168.4.1:80
[  7495][W][WebServer.cpp:436] send(): content length is zero
[  7761][V][WebServer.cpp:296] handleClient(): New client: client.localIP()=192.168.4.1
[  7764][V][Parsing.cpp:122] _parseRequest(): method: GET url: /connecttest.txt search: 
[  7766][V][Parsing.cpp:226] _parseRequest(): headerName: Cache-Control
[  7772][V][Parsing.cpp:227] _parseRequest(): headerValue: no-cache
[  7778][V][Parsing.cpp:226] _parseRequest(): headerName: Connection
[  7784][V][Parsing.cpp:227] _parseRequest(): headerValue: Close
[  7790][V][Parsing.cpp:226] _parseRequest(): headerName: Pragma
[  7795][V][Parsing.cpp:227] _parseRequest(): headerValue: no-cache
[  7802][V][Parsing.cpp:226] _parseRequest(): headerName: User-Agent
[  7808][V][Parsing.cpp:227] _parseRequest(): headerValue: Microsoft NCSI
[  7814][V][Parsing.cpp:226] _parseRequest(): headerName: Host
[  7820][V][Parsing.cpp:227] _parseRequest(): headerValue: www.msftconnecttest.com
[  7827][V][Parsing.cpp:254] _parseArguments(): args: 
[  7832][V][Parsing.cpp:237] _parseRequest(): Request: /connecttest.txt
[  7838][V][Parsing.cpp:238] _parseRequest():  Arguments: 
[  7844][E][WebServer.cpp:649] _handleRequest(): request handler not found
Request for www.msftconnecttest.com redirected to 192.168.4.1:80
[  7861][W][WebServer.cpp:436] send(): content length is zero
[ 37875][V][WebServer.cpp:296] handleClient(): New client: client.localIP()=192.168.4.1
[ 37876][V][Parsing.cpp:122] _parseRequest(): method: GET url: /connecttest.txt search: 
[ 37880][V][Parsing.cpp:226] _parseRequest(): headerName: Connection
[ 37886][V][Parsing.cpp:227] _parseRequest(): headerValue: Close
[ 37891][V][Parsing.cpp:226] _parseRequest(): headerName: User-Agent
[ 37897][V][Parsing.cpp:227] _parseRequest(): headerValue: Microsoft NCSI
[ 37904][V][Parsing.cpp:226] _parseRequest(): headerName: Host
[ 37909][V][Parsing.cpp:227] _parseRequest(): headerValue: www.msftconnecttest.com
[ 37917][V][Parsing.cpp:254] _parseArguments(): args: 
[ 37922][V][Parsing.cpp:237] _parseRequest(): Request: /connecttest.txt
[ 37928][V][Parsing.cpp:238] _parseRequest():  Arguments: 
[ 37933][E][WebServer.cpp:649] _handleRequest(): request handler not found
Request for www.msftconnecttest.com redirected to 192.168.4.1:80
[ 37951][W][WebServer.cpp:436] send(): content length is zero
[ 38218][V][WebServer.cpp:296] handleClient(): New client: client.localIP()=192.168.4.1
[ 38219][V][Parsing.cpp:122] _parseRequest(): method: GET url: /connecttest.txt search: 
[ 38223][V][Parsing.cpp:226] _parseRequest(): headerName: Connection
[ 38229][V][Parsing.cpp:227] _parseRequest(): headerValue: Close
[ 38234][V][Parsing.cpp:226] _parseRequest(): headerName: User-Agent
[ 38240][V][Parsing.cpp:227] _parseRequest(): headerValue: Microsoft NCSI
[ 38247][V][Parsing.cpp:226] _parseRequest(): headerName: Host
[ 38252][V][Parsing.cpp:227] _parseRequest(): headerValue: www.msftconnecttest.com
[ 38260][V][Parsing.cpp:254] _parseArguments(): args: 
[ 38265][V][Parsing.cpp:237] _parseRequest(): Request: /connecttest.txt
[ 38271][V][Parsing.cpp:238] _parseRequest():  Arguments: 
[ 38276][E][WebServer.cpp:649] _handleRequest(): request handler not found
Request for www.msftconnecttest.com redirected to 192.168.4.1:80
[ 38294][W][WebServer.cpp:436] send(): content length is zero
[ 49703][V][WebServer.cpp:296] handleClient(): New client: client.localIP()=192.168.4.1
[ 49704][V][Parsing.cpp:122] _parseRequest(): method: GET url: / search: 
[ 49706][V][Parsing.cpp:226] _parseRequest(): headerName: Host
[ 49712][V][Parsing.cpp:227] _parseRequest(): headerValue: 192.168.4.1
[ 49718][V][Parsing.cpp:226] _parseRequest(): headerName: Connection
[ 49724][V][Parsing.cpp:227] _parseRequest(): headerValue: keep-alive
[ 49730][V][Parsing.cpp:226] _parseRequest(): headerName: Cache-Control
[ 49737][V][Parsing.cpp:227] _parseRequest(): headerValue: max-age=0
[ 49743][V][Parsing.cpp:226] _parseRequest(): headerName: Upgrade-Insecure-Requests
[ 49750][V][Parsing.cpp:227] _parseRequest(): headerValue: 1
[ 49756][V][Parsing.cpp:226] _parseRequest(): headerName: User-Agent
[ 49762][V][Parsing.cpp:227] _parseRequest(): headerValue: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
[ 49777][V][Parsing.cpp:226] _parseRequest(): headerName: Accept
[ 49782][V][Parsing.cpp:227] _parseRequest(): headerValue: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
[ 49799][V][Parsing.cpp:226] _parseRequest(): headerName: Accept-Encoding
[ 49806][V][Parsing.cpp:227] _parseRequest(): headerValue: gzip, deflate
[ 49812][V][Parsing.cpp:226] _parseRequest(): headerName: Accept-Language
[ 49819][V][Parsing.cpp:227] _parseRequest(): headerValue: ru-RU,ru;q=0.9,en-GB;q=0.8,en;q=0.7,en-US;q=0.6
[ 49828][V][Parsing.cpp:254] _parseArguments(): args: 
[ 49833][V][Parsing.cpp:237] _parseRequest(): Request: /
[ 49838][V][Parsing.cpp:238] _parseRequest():  Arguments: 
[ 49843][V][main.cpp:84] handle_root(): Handle root
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x40094bfb  PS      : 0x00060d30  A0      : 0x80094e50  A1      : 0x3ffb1ac0  
A2      : 0xffffffff  A3      : 0x00000000  A4      : 0x0000001c  A5      : 0x3ffb1b40  
A6      : 0x00000000  A7      : 0x00000001  A8      : 0xffffffff  A9      : 0x00000009  
A10     : 0x00000000  A11     : 0x6c7092b8  A12     : 0x6c7092b8  A13     : 0x3ffc7098  
A14     : 0x00060d20  A15     : 0x00000001  SAR     : 0x0000001b  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000013  LBEG    : 0x4008b464  LEND    : 0x4008b46f  LCOUNT  : 0x00000000  

Backtrace: 0x40094bf8:0x3ffb1ac0 0x40094e4d:0x3ffb1ae0 0x400950cf:0x3ffb1b00 0x40114b36:0x3ffb1b20 0x400e752a:0x3ffb1b60 0x400d756b:0x3ffb1ba0 0x40179ebd:0x3ffb20d0 0x400e056e:0x3ffb20f0 0x400e0615:0x3ffb2110 0x400e06fb:0x3ffb2150 0x400e093a:0x3ffb21c0 0x4017a681:0x3ffb2230 0x400e53d1:0x3ffb2250 0x400d6dfe:0x3ffb2270 0x400ea9dd:0x3ffb2290

ELF file SHA256: b43a790a6f7e33aa

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
[     4][V][WiFiServer.h:42] WiFiServer(): WiFiServer::WiFiServer(port=80, ...)
[     4][V][WebServer.cpp:87] WebServer(): WebServer::Webserver(port=80)
[    31][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
[   479][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled
[   510][I][main.cpp:396] setup(): CPU Freq: 240 Mhz
[   510][I][main.cpp:397] setup(): Free heap: 248388 bytes
[   510][I][main.cpp:398] setup(): SDK version: v4.4.4
[   514][I][main.cpp:399] setup(): Starting ESP32CAM-RTSP...
[   519][V][main.cpp:404] setup(): PSRAM found and initialized
Config version: 1.5
Config size: 455
Loading configurations
[iwcAll]
|-- [iwcSys]
|   |-- 'iwcThingName' with value: 'ESP32CAM-RTSP'
|   |-- 'iwcApPassword' with value: <hidden>
|   |-- [iwcWifi0]
|   |   |-- 'iwcWifiSsid' with value: 'Keenetic_Main'
|   |   \-- 'iwcWifiPassword' with value: <hidden>
|   \-- 'iwcApTimeout' with value: '30'
|-- [iwcCustom]
|   |-- [board]
|   |   \-- 'bt' with value: 'ESP32CAM'
|   |-- [camera]
|   |   |-- 'fd' with value: '100'
|   |   |-- 'fs' with value: 'SVGA (800x600)'
|   |   |-- 'q' with value: '12'
|   |   |-- 'eps' with value: '0'
|   |   |-- 'fb' with value: '1'
|   |   |-- 'b' with value: '0'
|   |   |-- 'c' with value: '0'
|   |   |-- 's' with value: '0'
|   |   |-- 'e' with value: 'Normal'
|   |   |-- 'wb' with value: '1'
|   |   |-- 'awbg' with value: '1'
|   |   |-- 'wbm' with value: 'Auto'
|   |   |-- 'ec' with value: '1'
|   |   |-- 'aec2' with value: '1'
|   |   |-- 'ael' with value: '0'
|   |   |-- 'aecv' with value: '300'
|   |   |-- 'gc' with value: '1'
|   |   |-- 'agcg' with value: '0'
|   |   |-- 'gcl' with value: '2X'
|   |   |-- 'bpc' with value: '0'
|   |   |-- 'wpc' with value: '1'
|   |   |-- 'rg' with value: '1'
|   |   |-- 'lenc' with value: '1'
|   |   |-- 'hm' with value: '0'
|   |   |-- 'vm' with value: '0'
|   |   |-- 'dcw' with value: '1'
|   |   \-- 'cb' with value: '0'
|   \-- [io]
|       \-- 'li' with value: '0'
\-- [hidden]
[   658][V][main.cpp:282] initialize_camera(): initialize_camera
[   658][I][main.cpp:283] initialize_camera(): Camera config: ESP32CAM
[   664][I][main.cpp:289] initialize_camera(): Frame size: SVGA (800x600)
[   670][I][main.cpp:291] initialize_camera(): JPEG quality: 12
[   676][I][main.cpp:292] initialize_camera(): Frame duration: 100 ms
[   682][I][main.cpp:296] initialize_camera(): Enable PSRAM: 0
[   688][I][main.cpp:297] initialize_camera(): Frame buffers: 1
[   693][I][main.cpp:308] initialize_camera(): PSRAM disabled
E (703) camera: Camera probe failed with error 0x105(ESP_ERR_NOT_FOUND)
[   733][E][main.cpp:452] setup(): Failed to initialize camera: 0x105. Type: ESP32CAM, frame size: SVGA (800x600), frame rate: 100 ms, jpeg quality: 12
AP password was not set in configuration
State changing from: 0 to 1
[   771][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 0 - WIFI_READY
Setting up AP: ESP32CAM-RTSP
With default password: <hidden>
AP IP address: [   865][V][WiFiGeneric.cpp:392] _arduino_event_cb(): AP Started
192.[   870][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 10 - AP_START
[   872][V][WiFiGeneric.cpp:395] _arduino_event_cb(): AP Stopped
168.4.1
[   880][V][WiFiGeneric.cpp:392] _arduino_event_cb(): AP Started
[   879][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 11 - AP_STOP
[   893][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 10 - AP_START
AP password was not set.
Will stay in AP mode.
State changed from: 0 to 1
Connection to AP.
[  4460][V][WiFiGeneric.cpp:407] _arduino_event_cb(): AP Station Connected: MAC: 80:e6:50:17:69:58, AID: 1
[  4461][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 12 - AP_STACONNECTED
[  4487][V][WiFiGeneric.cpp:421] _arduino_event_cb(): AP Station IP Assigned:192.168.4.2
[  4487][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 14 - AP_STAIPASSIGNED
[  4601][V][WebServer.cpp:296] handleClient(): New client: client.localIP()=192.168.4.1
[  4604][V][Parsing.cpp:122] _parseRequest(): method: GET url: /connecttest.txt search: 
[  4606][V][Parsing.cpp:226] _parseRequest(): headerName: Cache-Control
[  4612][V][Parsing.cpp:227] _parseRequest(): headerValue: no-cache
[  4618][V][Parsing.cpp:226] _parseRequest(): headerName: Connection
[  4624][V][Parsing.cpp:227] _parseRequest(): headerValue: Close
[  4630][V][Parsing.cpp:226] _parseRequest(): headerName: Pragma
[  4636][V][Parsing.cpp:227] _parseRequest(): headerValue: no-cache
[  4642][V][Parsing.cpp:226] _parseRequest(): headerName: User-Agent
[  4648][V][Parsing.cpp:227] _parseRequest(): headerValue: Microsoft NCSI
[  4654][V][Parsing.cpp:226] _parseRequest(): headerName: Host
[  4660][V][Parsing.cpp:227] _parseRequest(): headerValue: www.msftconnecttest.com
[  4667][V][Parsing.cpp:254] _parseArguments(): args: 
[  4672][V][Parsing.cpp:237] _parseRequest(): Request: /connecttest.txt
[  4678][V][Parsing.cpp:238] _parseRequest():  Arguments: 
[  4684][E][WebServer.cpp:649] _handleRequest(): request handler not found
Request for www.msftconnecttest.com redirected to 192.168.4.1:80
[  4701][W][WebServer.cpp:436] send(): content length is zero
[  4966][V][WebServer.cpp:296] handleClient(): New client: client.localIP()=192.168.4.1
[  4967][V][Parsing.cpp:122] _parseRequest(): method: GET url: /connecttest.txt search: 
[  4971][V][Parsing.cpp:226] _parseRequest(): headerName: Cache-Control
[  4977][V][Parsing.cpp:227] _parseRequest(): headerValue: no-cache
[  4983][V][Parsing.cpp:226] _parseRequest(): headerName: Connection
[  4989][V][Parsing.cpp:227] _parseRequest(): headerValue: Close
[  4995][V][Parsing.cpp:226] _parseRequest(): headerName: Pragma
[  5000][V][Parsing.cpp:227] _parseRequest(): headerValue: no-cache
[  5007][V][Parsing.cpp:226] _parseRequest(): headerName: User-Agent
[  5013][V][Parsing.cpp:227] _parseRequest(): headerValue: Microsoft NCSI
[  5019][V][Parsing.cpp:226] _parseRequest(): headerName: Host
[  5025][V][Parsing.cpp:227] _parseRequest(): headerValue: www.msftconnecttest.com
[  5032][V][Parsing.cpp:254] _parseArguments(): args: 
[  5037][V][Parsing.cpp:237] _parseRequest(): Request: /connecttest.txt
[  5043][V][Parsing.cpp:238] _parseRequest():  Arguments: 
[  5049][E][WebServer.cpp:649] _handleRequest(): request handler not found
Request for www.msftconnecttest.com redirected to 192.168.4.1:80
[  5066][W][WebServer.cpp:436] send(): content length is zero

**Comment by rzeldent** [comment]
Hi Ivan,

Can you try clearing the EEPROM?

In platformio:

Run Task- PlatformIO: Erase FLASH

Maybe this helps...

**Comment by rzeldent** [comment]
Also, see that your camera doe not initialize. Try to uncheck the "use PSRAM" option and set the frame buffers to 1.

**Comment by rzeldent** [comment]
Could you also enable the exception decoder in Platformio:

https://community.platformio.org/t/how-do-i-use-esp32-exception-decoder/22789

This will hopefully provider some more info...

**Comment by ivanshateev** [comment]
I erased the EEROM in this way (via the Arduino IDE):
#include <EEPROM.h>

void setup() {
  
  EEPROM.begin(512);
  // Записываем 0 во все 512 байт EEPROM
  for (int i = 0; i < 512; i++) {
    EEPROM.write(i, 0);
    
  }

  EEPROM.end();
}

void loop() {
}


But now the next one. 
JPEG Motion stream - working. 
RTSP camera stream - Error. (VLC cannot open MRL 'rtsp://192.168.4.1:554/mjpeg/1'. Look for more details in the log file.)

**Comment by rzeldent** [comment]
Can you check it when connected to the access point?

**Comment by ivanshateev** [comment]
In the diagnostics on the web page it says - RTSP is disabled. How to turn it on?

Connected to point: ESP32CAM-RTSP.

ESP32 SDK Version: v4.4.4
CPU model: ESP32-D0WDQ5 rev. 1
CPU speed: 240 Mhz
CPU cores: 2
RAM size: 264.31 KB
PSRAM size: 4 MB
Flash size: 4 MB

Diagnostics
Uptime: 00:01:57
RTSP sessions: RTSP server disabled
Free heap: 55.88 KB
Max free block: 35.99 KB

**Comment by rzeldent** [comment]
RTSP is only enabled if it is connected to an access point. The 192.168.4.1 is only for configuration/testing.

**Comment by ivanshateev** [comment]
Everything is working.  Thank you.
