### ISSUE TITLE
Multiclient

### ISSUE THREAD

**Issue by RichMar** [rzeldent/esp32cam-rtsp#57]
I like your solution for this camera. Are you ever planning a multi-client extension?

**Comment by rzeldent** [comment]
Hi Rich,

You mean that more than one client can connect and watch at the same time?
This is present for RTSP (not for Motion JPEG). However, the power of the ESP32 has severe limitations and as you can read in the issues, is already reaching its limits...

Enjoy!

Rene

**Comment by RichMar** [comment]
Hi Rene,
Yes, I mean more than one client. I'm sorry, it was my ignorance.
But I will still ask, would posting stremp over blynk.io be possible? It should be able to split the stream for more users or?
There is a need to write values for in the firmware:
#define BLYNK_TEMPLATE_ID
#define BLYNK_TEMPLATE_NAME

Rich

**Comment by kvikindi** [comment]
Hey there RichMar - You might be able to use something like [go2rtc](https://github.com/AlexxIT/go2rtc) to _split_ the stream. It would however require go2rtc to be running on a separate machine, and it's a bit of a handful wrapping your head around it.

Let us know how it goes!
Ragnar
