### ISSUE TITLE
Change Wifi Mode

### ISSUE THREAD

**Issue by spawn451** [rzeldent/esp32cam-rtsp#59]
Hello, how can I change the Wifi mode ? I don't want it to run as an AP but use the Station mode so I can access the rtsp url in my local network.

**Comment by wsAndy** [comment]
how to change the wifi mode?

**Comment by rzeldent** [comment]
I think you can use it also as AP, just connect to the IP Address of the AP...

**Comment by wsAndy** [comment]
Well, AP mode return 192.168xxx, cannot connect it by others in the same LAN.



发自我的iPhone


------------------ Original ------------------
From: Rene ***@***.***&gt;
Date: Wed,Nov 13,2024 7:02 PM
To: rzeldent/esp32cam-rtsp ***@***.***&gt;
Cc: Sheng Wang ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [rzeldent/esp32cam-rtsp] Change Wifi Mode (Issue #59)





 
I think you can use it also as AP, just connect to the IP Address of the AP...
