### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by saaapaaa** [rzeldent/esp32cam-rtsp#61]
Hello and thanks for share this work.

This seems best existing interface for ESP32 CAM for Homekit but somehow not working for me.
I managed to run it on my ESP32 but it seems so slow and RTSP video is not working.
From my side only snapshot and JPEG Motion stream are working but those are super slow.
I am trying different type of pwr input but in vain... wifi signal strength is around 50-60.
And sometimes ESP32 board gets quite hot.

I have zero knowledge of coding so I need help from creator..
How can I access to the log file to share?

![image](https://user-images.githubusercontent.com/53567787/232006216-4cfc49bd-745d-4b2b-aab0-91a3523088a3.png)

**Comment by rzeldent** [comment]
HI saupac,

I do not know exactly what's going on. It depends also on the RTSP client you're using.
If the MPEG stream is already slow, maybe decreasing the resolution helps.
If you connect a serial terminal to the ESP32_CAM, with 15200 baud the logging can be read...

Good luck!
