### ISSUE TITLE
is there a way to rotate by 90 degrees?

### ISSUE THREAD

**Issue by bltDefender** [rzeldent/esp32cam-rtsp#63]
h flip and v flip are great, I mounted a fish eye lens cam (DCX-OV2) and now the video comes in with 90 degrees. Any way to get this fixed?

**Comment by rzeldent** [comment]
Hi bitDefender,

Not with the current settings/options in the API. Maybe ffmpeg post processing?
Or rotate the camera?

**Comment by john-arvid** [comment]
you can do this: https://timsblogplace.blogspot.com/2022/01/esp32-cam-rotating-camera.html
