### ISSUE TITLE
Adding a custom ESP32 Board

### ISSUE THREAD

**Issue by T3AR5** [rzeldent/esp32cam-rtsp#65]
Hi,

I am working on a custom image sensor PCB for my master thesis and would like to know, if its possible to adjust this firmware to work with the ESP32S3WROOM and my pinout? And how would I start on that?

I am fairly new to firmware programming and only found the camera pinout setting, which I could adjust to my schematic, but the other settings are taken from online resources as far as I can see?

I have attached the schematic for my PCB and would be very thankful for any help!
[Circuit_Diagram_ESP32_Image_Sensor_Board.PDF](https://github.com/rzeldent/esp32cam-rtsp/files/11423515/Circuit_Diagram_ESP32_Image_Sensor_Board.PDF)

Currently I have added this to the lookup_camera_config:

> constexpr camera_config_t esp32s3_settings = {
>       .pin_pwdn = 48,
>       .pin_reset = -1,
>       .pin_xclk = 15,
>       .pin_sscb_sda = 4,
>       .pin_sscb_scl = 5,
>       .pin_d7 = 16,
>       .pin_d6 = 17,
>       .pin_d5 = 18,
>       .pin_d4 = 12,
>       .pin_d3 = 10,
>       .pin_d2 = 8,
>       .pin_d1 = 9,
>       .pin_d0 = 11,
>       .pin_vsync = 6,
>       .pin_href = 7,
>       .pin_pclk = 13,
>       .xclk_freq_hz = 20000000,
>       .ledc_timer = LEDC_TIMER_1,
>       .ledc_channel = LEDC_CHANNEL_1,
>       .pixel_format = PIXFORMAT_JPEG,
>       .frame_size = FRAMESIZE_SVGA,
>       .jpeg_quality = 12,
>       .fb_count = 2};
>   
>   constexpr const camera_config_entry_t camera_configs[] = {
>       {"ESP32CAM", esp32cam_settings},
>       {"AI THINKER", esp32cam_aithinker_settings},
>       {"TTGO T-CAM", esp32cam_ttgo_t_settings},
>       {"M5 STACK", esp32cam_m5stack_settings},
>       {"WROVER KIT", esp32cam_wrover_kit_settings},
>       {"ESO32S3", esp32s3_settings}};

Is this correct so far and what else do I need to change?

 Thanks in advance!

**Comment by rzeldent** [comment]
Hi T3AR5,

Yes, This should be sufficient to be able to address the camera. However, make sure the parameters and camera type are correct!

**Comment by T3AR5** [comment]
Hi rzeldent and thanks for your fast reply!

I did the above edits and get the error "A fatal error occurred: This chip is ESP32-S3 not ESP32. Wrong --chip argument?" when uploading the code.
I am aware, that I am using a ESP32S3, but where do I need to update the parameter for this? thanks again!

**Comment by rzeldent** [comment]
Aha,

This must be updated in the platformio.ini file. The setting board = 

See https://docs.platformio.org/en/latest/boards/espressif32/esp32-c3-devkitc-02.html (but maybe you have another board)

**Comment by T3AR5** [comment]
I was able to set it up with your advice and am able to connect over wifi to the esp.

it also says, that the camera was initialized successfully, but I cant get a stream or snapshot yet.

Also it says PSRAM size 0B (prob due to the dev kit chosen as board in vs code), but I have a esp32s3 with 8mb psram. i tried overriding the inital setting using "board_upload.maximum_ram_size = 8192000" but didnt change anything :/

**Comment by rzeldent** [comment]
Hi T3AR5,

It is possible your board does not have PSRAM. That is no problem; not all boards have that. This will only limit the resolution/frame rate.

The camera that is used is an OV2640. If you do not have a snapshot there might be some incompatibility...
No errors or logging?

Rene

**Comment by T3AR5** [comment]
Hi Rene,

my board does has the PSRAM, the modul says N16R8, but good to know, that that should atleast not prohibit me from using the camera.
I use a OV2640 as well and it works with your firmware and a ESP32CAM, but not with my custom board as of yet.
Will try to get a log tomorrow.

thanks again for you help, really appreciated =)

**Comment by T3AR5** [comment]
Finally got around to test again, first made sure that the boards do have the PSRAM with an Arduino script :D 
maybe I need to change something to enable OPI PSRAM.

For the log I am not sure what to look for, it seems like it crashed and rebooted?

Here is the log from starting the board, connecting to the webserver and trying to start a RTTSP camera stream:

> ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x9 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a38
entry 0x403c98d4
[   202][V][WiFiServer.h:42] WiFiServer(): WiFiServer::WiFiServer(port=80, ...)
[   202][V][WebServer.cpp:87] WebServer(): WebServer::Webserver(port=80)
E (224) psram: PSRAM ID read error: 0x00ffffff
[   223][W][esp32-hal-psram.c:71] psramInit(): PSRAM init failed!
[   246][I][main.cpp:395] setup(): CPU Freq: 240 Mhz
[   246][I][main.cpp:396] setup(): Free heap: 290140 bytes
[   247][I][main.cpp:397] setup(): SDK version: v4.4.4
[   250][I][main.cpp:398] setup(): Starting ESP32CAM-RTSP...
Config version: 1.5
Config size: 455
Loading configurations
[iwcAll]
|-- [iwcSys]
|   |-- 'iwcThingName' with value: 'ESP32CAM-RTSP'
|   |-- 'iwcApPassword' with value: <hidden>
|   |-- [iwcWifi0]
|   |   |-- 'iwcWifiSsid' with value: '7490'
|   |   \-- 'iwcWifiPassword' with value: <hidden>
|   \-- 'iwcApTimeout' with value: '5'
|-- [iwcCustom]
|   |-- [board]
|   |   \-- 'bt' with value: 'ESP32S3'
|   |-- [camera]
|   |   |-- 'fd' with value: '100'
|   |   |-- 'fs' with value: 'QQVGA (160x120)'
|   |   |-- 'q' with value: '12'
|   |   |-- 'eps' with value: '1'
|   |   |-- 'fb' with value: '1'
|   |   |-- 'b' with value: '0'
|   |   |-- 'c' with value: '0'
|   |   |-- 's' with value: '0'
|   |   |-- 'e' with value: 'Normal'
|   |   |-- 'wb' with value: '1'
|   |   |-- 'awbg' with value: '1'
|   |   |-- 'wbm' with value: 'Auto'
|   |   |-- 'ec' with value: '1'
|   |   |-- 'aec2' with value: '1'
|   |   |-- 'ael' with value: '0'
|   |   |-- 'aecv' with value: '300'
|   |   |-- 'gc' with value: '1'
|   |   |-- 'agcg' with value: '0'
|   |   |-- 'gcl' with value: '2X'
|   |   |-- 'bpc' with value: '0'
|   |   |-- 'wpc' with value: '1'
|   |   |-- 'rg' with value: '1'
|   |   |-- 'lenc' with value: '1'
|   |   |-- 'hm' with value: '0'
|   |   |-- 'vm' with value: '0'
|   |   |-- 'dcw' with value: '1'
|   |   \-- 'cb' with value: '0'
|   \-- [io]
|       \-- 'li' with value: '0'
\-- [hidden]
[   387][V][main.cpp:278] initialize_camera(): initialize_camera
[   388][I][main.cpp:279] initialize_camera(): Camera config: ESP32S3
[   394][I][main.cpp:285] initialize_camera(): Frame size: QQVGA (160x120)
[   400][I][main.cpp:287] initialize_camera(): JPEG quality: 12
[   406][I][main.cpp:288] initialize_camera(): Frame duration: 100 ms
[   412][I][main.cpp:292] initialize_camera(): Enable PSRAM: 1
[   417][I][main.cpp:293] initialize_camera(): Frame buffers: 1
[   423][I][main.cpp:304] initialize_camera(): PSRAM disabled
State changing from: 0 to 2
[   677][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 0 - WIFI_READY
Setting up AP: ESP32CAM-RTSP
Use password: <hidden>
[   720][V][WiFiGeneric.cpp:392] _arduino_event_cb(): AP Started
[   722][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 10 - AP_START
AP IP address: 192.168.4.1
[  1436][V][WiFiGeneric.cpp:395] _arduino_event_cb(): AP Stopped
[  1437][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 11 - AP_STOP
[  1438][V][WiFiGeneric.cpp:392] _arduino_event_cb(): AP Started
[  1444][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 10 - AP_START
AP timeout (ms): 5000
State changed from: 0 to 2
State changing from: 2 to 3
[  6469][V][WiFiGeneric.cpp:395] _arduino_event_cb(): AP Stopped
[  6472][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 11 - AP_STOP
[  6473][V][WiFiGeneric.cpp:392] _arduino_event_cb(): AP Started
ConnectiE (6479) wifi_init_default: esp_wifi_get_mac failed with 12289
ng to [[  6485][V][WiFiGeneric.cpp:395] _arduino_event_cb(): AP Stopped
[  6479][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 10 - AP_START
[  6499][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 11 - AP_STOP
7490] (password is hidden)
WiFi timeout (ms): 30000
[  6532][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 0 - WIFI_READY
[  6539][V][WiFiGeneric.cpp:340] _arduino_event_cb(): STA Started
[  6542][V][WiFiGeneric.cpp:97] set_esp_interface_ip(): Configuring Station static IP: 0.0.0.0, MASK: 0.0.0.0, GW: 0.0.0.0
[  6542][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 2 - STA_START
State changed from: 2 to 3
[  6578][V][WiFiGeneric.cpp:362] _arduino_event_cb(): STA Disconnected: SSID: 7490, BSSID: 5c:49:79:4f:09:d9, Reason: 202
[  6579][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 5 - STA_DISCONNECTED
[  6586][W][WiFiGeneric.cpp:1057] _eventCallback(): Reason: 202 - AUTH_FAIL
[  6593][D][WiFiGeneric.cpp:1077] _eventCallback(): WiFi Reconnect Running
[  6602][V][WiFiGeneric.cpp:97] set_esp_interface_ip(): Configuring Station static IP: 0.0.0.0, MASK: 0.0.0.0, GW: 0.0.0.0
[  6677][V][WiFiGeneric.cpp:355] _arduino_event_cb(): STA Connected: SSID: 7490, BSSID: 5c:49:79:4f:09:d9, Channel: 6, Auth: WPA2_PSK
[  6678][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 4 - STA_CONNECTED
[  6700][V][WiFiGeneric.cpp:369] _arduino_event_cb(): STA Got New IP:192.168.123.80
[  6702][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 7 - STA_GOT_IP
[  6705][D][WiFiGeneric.cpp:1098] _eventCallback(): STA IP: 192.168.123.80, MASK: 255.255.255.0, GW: 192.168.123.1
WiFi connected
IP address: 192.168.123.80
State changing from: 3 to 4
Active mDNS services: 4 
Accepting connection
[  9831][V][main.cpp:353] on_connected(): on_connected
[  9845][I][ArduinoOTA.cpp:141] begin(): OTA server at: esp32-f412fad6c5b8.local:3232
[  9845][V][main.cpp:345] start_rtsp_server(): start_rtsp_server
[  9847][V][WiFiServer.h:42] WiFiServer(): WiFiServer::WiFiServer(port=554, ...)
[  9855][I][rtsp_server.cpp:9] rtsp_server(): Starting RTSP server
State changed from: 3 to 4
[ 36269][V][WebServer.cpp:296] handleClient(): New client: client.localIP()=192.168.123.80
[ 36270][V][Parsing.cpp:122] _parseRequest(): method: GET url: / search: 
[ 36273][V][Parsing.cpp:226] _parseRequest(): headerName: Host
[ 36278][V][Parsing.cpp:227] _parseRequest(): headerValue: 192.168.123.80
[ 36285][V][Parsing.cpp:226] _parseRequest(): headerName: Connection
[ 36291][V][Parsing.cpp:227] _parseRequest(): headerValue: keep-alive
[ 36297][V][Parsing.cpp:226] _parseRequest(): headerName: Authorization
[ 36303][V][Parsing.cpp:227] _parseRequest(): headerValue: Basic YWRtaW46UGFzc3dvcnQ=
[ 36311][V][Parsing.cpp:226] _parseRequest(): headerName: Upgrade-Insecure-Requests
[ 36318][V][Parsing.cpp:227] _parseRequest(): headerValue: 1
[ 36324][V][Parsing.cpp:226] _parseRequest(): headerName: User-Agent
[ 36330][V][Parsing.cpp:227] _parseRequest(): headerValue: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
[ 36346][V][Parsing.cpp:226] _parseRequest(): headerName: Accept
[ 36350][V][Parsing.cpp:227] _parseRequest(): headerValue: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
[ 36368][V][Parsing.cpp:226] _parseRequest(): headerName: Accept-Encoding
[ 36374][V][Parsing.cpp:227] _parseRequest(): headerValue: gzip, deflate
[ 36381][V][Parsing.cpp:226] _parseRequest(): headerName: Accept-Language
[ 36387][V][Parsing.cpp:227] _parseRequest(): headerValue: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
[ 36395][V][Parsing.cpp:254] _parseArguments(): args: 
[ 36400][V][Parsing.cpp:237] _parseRequest(): Request: /
[ 36405][V][Parsing.cpp:238] _parseRequest():  Arguments: 
[ 36411][V][main.cpp:83] handle_root(): Handle root
[ 36582][V][WebServer.cpp:296] handleClient(): New client: client.localIP()=192.168.123.80
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x420163af  PS      : 0x00060530  A0      : 0x8208ce20  A1      : 0x3fcebe70  
A2      : 0x00000000  A3      : 0x3fcb91ac  A4      : 0x803808ad  A5      : 0x3fcebd90  
A6      : 0x00060023  A7      : 0x00000003  A8      : 0x820163ac  A9      : 0x3fcebe50  
A10     : 0x3fcba754  A11     : 0x3fcbadbc  A12     : 0x80377c7b  A13     : 0x3fcebd60  
A14     : 0x00000001  A15     : 0x3fcea120  SAR     : 0x0000001e  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000008  LBEG    : 0x40056f5c  LEND    : 0x40056f72  LCOUNT  : 0xffffffff  


Backtrace: 0x420163ac:0x3fcebe70 0x4208ce1d:0x3fcebe90 0x420177d2:0x3fcebeb0 0x4201792b:0x3fcebef0 0x42017551:0x3fcebf40 0x4201758c:0x3fcebf60 0x420072d7:0x3fcebf80 0x4201ac21:0x3fcebfa0




ELF file SHA256: e27e5ad908a872c9

Rebooting...
�ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x9 (SPI_FAST_FLASH_BOOT)
Saved PC:0x420a546e
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a38
entry 0x403c98d4
[   208][V][WiFiServer.h:42] WiFiServer(): WiFiServer::WiFiServer(port=80, ...)
[   208][V][WebServer.cpp:87] WebServer(): WebServer::Webserver(port=80)
E (230) psram: PSRAM ID read error: 0x00ffffff
[   229][W][esp32-hal-psram.c:71] psramInit(): PSRAM init failed!
[   252][I][main.cpp:395] setup(): CPU Freq: 240 Mhz
[   252][I][main.cpp:396] setup(): Free heap: 290140 bytes
[   253][I][main.cpp:397] setup(): SDK version: v4.4.4
[   256][I][main.cpp:398] setup(): Starting ESP32CAM-RTSP...
Config version: 1.5
Config size: 455
Loading configurations
[iwcAll]
|-- [iwcSys]
|   |-- 'iwcThingName' with value: 'ESP32CAM-RTSP'
|   |-- 'iwcApPassword' with value: <hidden>
|   |-- [iwcWifi0]
|   |   |-- 'iwcWifiSsid' with value: '7490'
|   |   \-- 'iwcWifiPassword' with value: <hidden>
|   \-- 'iwcApTimeout' with value: '5'
|-- [iwcCustom]
|   |-- [board]
|   |   \-- 'bt' with value: 'ESP32S3'
|   |-- [camera]
|   |   |-- 'fd' with value: '100'
|   |   |-- 'fs' with value: 'QQVGA (160x120)'
|   |   |-- 'q' with value: '12'
|   |   |-- 'eps' with value: '1'
|   |   |-- 'fb' with value: '1'
|   |   |-- 'b' with value: '0'
|   |   |-- 'c' with value: '0'
|   |   |-- 's' with value: '0'
|   |   |-- 'e' with value: 'Normal'
|   |   |-- 'wb' with value: '1'
|   |   |-- 'awbg' with value: '1'
|   |   |-- 'wbm' with value: 'Auto'
|   |   |-- 'ec' with value: '1'
|   |   |-- 'aec2' with value: '1'
|   |   |-- 'ael' with value: '0'
|   |   |-- 'aecv' with value: '300'
|   |   |-- 'gc' with value: '1'
|   |   |-- 'agcg' with value: '0'
|   |   |-- 'gcl' with value: '2X'
|   |   |-- 'bpc' with value: '0'
|   |   |-- 'wpc' with value: '1'
|   |   |-- 'rg' with value: '1'
|   |   |-- 'lenc' with value: '1'
|   |   |-- 'hm' with value: '0'
|   |   |-- 'vm' with value: '0'
|   |   |-- 'dcw' with value: '1'
|   |   \-- 'cb' with value: '0'
|   \-- [io]
|       \-- 'li' with value: '0'
\-- [hidden]
[   393][V][main.cpp:278] initialize_camera(): initialize_camera
[   394][I][main.cpp:279] initialize_camera(): Camera config: ESP32S3
[   400][I][main.cpp:285] initialize_camera(): Frame size: QQVGA (160x120)
[   406][I][main.cpp:287] initialize_camera(): JPEG quality: 12
[   412][I][main.cpp:288] initialize_camera(): Frame duration: 100 ms
[   418][I][main.cpp:292] initialize_camera(): Enable PSRAM: 1
[   423][I][main.cpp:293] initialize_camera(): Frame buffers: 1
[   429][I][main.cpp:304] initialize_camera(): PSRAM disabled
State changing from: 0 to 2
[   683][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 0 - WIFI_READY
Setting up AP: ESP32CAM-RTSP
Use password: <hidden>
[   725][V][WiFiGeneric.cpp:392] _arduino_event_cb(): AP Started
[   728][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 10 - AP_START
AP IP address: 192.168.4.1
[  1440][V][WiFiGeneric.cpp:395] _arduino_event_cb(): AP Stopped
[  1441][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 11 - AP_STOP
[  1442][V][WiFiGeneric.cpp:392] _arduino_event_cb(): AP Started
[  1448][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 10 - AP_START
AP timeout (ms): 5000
State changed from: 0 to 2
State changing from: 2 to 3
[  6471][V][WiFiGeneric.cpp:395] _arduino_event_cb(): AP Stopped
[  6471][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 11 - AP_STOP
[  6478][V][WiFiGeneric.cpp:392] _arduino_event_cb(): AP Started
[  6480][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 10 - AP_START
E (64C80) wifi_init_default: esp_wifi_get_mac failed with 12289
onnecting to [7490[  6491][V][WiFiGeneric.cpp:395] _arduino_event_cb(): AP Stopped
] (password is hidden)
WiFi timeout (ms): [  6502][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 11 - AP_STOP
30000
[  6528][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 0 - WIFI_READY
[  6536][V][WiFiGeneric.cpp:340] _arduino_event_cb(): STA Started
[  6539][V][WiFiGeneric.cpp:97] set_esp_interface_ip(): Configuring Station static IP: 0.0.0.0, MASK: 0.0.0.0, GW: 0.0.0.0
[  6539][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 2 - STA_START
State changed from: 2 to 3
[  6577][V][WiFiGeneric.cpp:362] _arduino_event_cb(): STA Disconnected: SSID: 7490, BSSID: 5c:49:79:4f:09:d9, Reason: 202
[  6578][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 5 - STA_DISCONNECTED
[  6585][W][WiFiGeneric.cpp:1057] _eventCallback(): Reason: 202 - AUTH_FAIL
[  6592][D][WiFiGeneric.cpp:1077] _eventCallback(): WiFi Reconnect Running
[  6601][V][WiFiGeneric.cpp:97] set_esp_interface_ip(): Configuring Station static IP: 0.0.0.0, MASK: 0.0.0.0, GW: 0.0.0.0
[  6673][V][WiFiGeneric.cpp:355] _arduino_event_cb(): STA Connected: SSID: 7490, BSSID: 5c:49:79:4f:09:d9, Channel: 6, Auth: WPA2_PSK
[  6675][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 4 - STA_CONNECTED
[  6698][V][WiFiGeneric.cpp:369] _arduino_event_cb(): STA Got New IP:192.168.123.80
[  6699][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 7 - STA_GOT_IP
[  6703][D][WiFiGeneric.cpp:1098] _eventCallback(): STA IP: 192.168.123.80, MASK: 255.255.255.0, GW: 192.168.123.1
WiFi connected
IP address: 192.168.123.80
State changing from: 3 to 4
Active mDNS services: 4 
Accepting connection
[  9829][V][main.cpp:353] on_connected(): on_connected
[  9843][I][ArduinoOTA.cpp:141] begin(): OTA server at: esp32-f412fad6c5b8.local:3232
[  9843][V][main.cpp:345] start_rtsp_server(): start_rtsp_server
[  9845][V][WiFiServer.h:42] WiFiServer(): WiFiServer::WiFiServer(port=554, ...)
[  9853][I][rtsp_server.cpp:9] rtsp_server(): Starting RTSP server
State changed from: 3 to 4

**Comment by rzeldent** [comment]
Hi T3ARS,

Looks like something goed wrong when starting to stream. Maybe the camera. Maybe you can enable the exception decoder (https://community.platformio.org/t/how-do-i-use-esp32-exception-decoder/22789) to get some more details...

Rene

**Comment by T3AR5** [comment]
Hi rzeldent,

the errors I got after decoding were, that it failed to get the framebuffer, the framesize or the framwidth.
Which of these errors I got depended on which camera application I launched, rtsp stream, jpeg stream or snapshot.

I soldered another PCB today and will try if there are any changes due to possible solder issues.

**Comment by T3AR5** [comment]
Just to let you know, I was able to make the board work, seems like the final problems were with a bad solder joint.

I only got some horizontal lines in the images depending on the chosen exposure and gain values, but otherwise its working fine.

So thank you very much for your inputs and help! Thanks to that I am able to present a working prototype for my master thesis :D

**Comment by rzeldent** [comment]
Hi T3AR5,

Very glad you found the issue and got it to work. I hope you get a good
grade!!!

Kind regards,

Rene

**Comment by curiegupta** [comment]
Hi,

I am new to platformio. I am working on a project that uses ESP32S3-EYE board.
With the ESP32CAM board, everything works perfectly fine.

I updated the lookup_camera_config to include camera pinout for the ESP32S3EYE board,
`constexpr const camera_config_entry_t camera_configs[] = {
    {"ESP32CAM", esp32cam_settings},
    {"AI THINKER", esp32cam_aithinker_settings},
    {"TTGO T-CAM", esp32cam_ttgo_t_settings},
    {"M5 STACK", esp32cam_m5stack_settings},
    {"WROVER KIT", esp32cam_wrover_kit_settings},
    {"ESP32S3EYE", esp32S3_settings}};`

I also made the following changes to the platformio.ini file,
`[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
; change microcontroller
board_build.mcu = esp32s3
; change MCU frequency
board_build.f_cpu = 240000000L`

I am getting errors while trying to build the project. It looks like a dependency on two of the libraries (Arduino.h and WiFiServer.h). I am not sure how to include them though.
Attaching the error logs for reference, 
[logs_12July2023_1.txt](https://github.com/rzeldent/esp32cam-rtsp/files/12028107/logs_12July2023_1.txt)


Any help would be appreciated! Thanks in advance.

Best regards.
:)

**Comment by curiegupta** [comment]
Hi, 
I was able to resolve this issue.
I deleted the platformio folder on my system and then re-started VSCode and let it install the platformio extension again. Apparently some libraries earlier were broken. 

Sharing my platformio.ini file just in case anyone needs reference

```.c
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
upload_protocol = esptool
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
monitor_filters = log2file, time, default, esp32_exception_decoder
build_flags = 
	-O2
	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
	-D LED_FLASH=4
	-D LED_BUILTIN=33
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-D IOTWEBCONF_PASSWORD_LEN=64
board_build.embed_txtfiles = 
	html/index.min.html
	html/restart.min.html
lib_deps = 
	prampec/IotWebConf @ ^3.2.1
	geeksville/Micro-RTSP @ ^0.1.6
	rzeldent/micro-moustache@^1.0.1
```
