### ISSUE TITLE
arduino

### ISSUE THREAD

**Issue by mhkjoon** [rzeldent/esp32cam-rtsp#66]
Hi
How can I upload your code on ESP32CAM using Arduino? Also, where is the Arduino code located in this program?

**Comment by rzeldent** [comment]
Hi mhkjoon,

This code is using the PlatformIO. This is a multiplatform embedded IDE.
With some modifications you should be able to get this running on the original Arduino platform by renaming main.cpp  to main.ino and setting other options/paths. However, I suggest you use Platformio. This is a plugin for Visual Studio code.

More information how to install this can be found in the documentation.

Kind regards,

Rene
