### ISSUE TITLE
Rotate image 90 degrees in http://192.168.4.1/stream

### ISSUE THREAD

**Issue by JavierSen** [rzeldent/esp32cam-rtsp#75]
Hi, I´m test your project, but my camara case is in horizontal.
Is it possible when you’re in stream mode, to rotate the image 90º? I don’t find option, and I think the only way would be an html. 
Thank you.

**Comment by rzeldent** [comment]
Hi Javier,

No, there are only options for flip horizontal and vertical. This is a camera setting.
I think you need some post processing to accomplish this...

Kind regards,

Rene

**Comment by john-arvid** [comment]
you can do this: https://timsblogplace.blogspot.com/2022/01/esp32-cam-rotating-camera.html
