### ISSUE TITLE
can not add this esp32-rtsp camera to blue iris

### ISSUE THREAD

**Issue by reno-pensando** [rzeldent/esp32cam-rtsp#79]
I have successfully loaded the firmware to the camera and I can view the rtsp stream through vlc player. However, I can not add this camera through rstp url.
Any suggestion? thx

**Comment by nickysemenza** [comment]
<img width="874" alt="image" src="https://github.com/rzeldent/esp32cam-rtsp/assets/707582/a8e82173-5de3-4ef9-8df0-ebee2a78ad4b">
i was able to get it to work like this

**Comment by rzeldent** [comment]
Hi Nick,

Does this work in the browser? If you go to 10.0.0.49/stream
