### ISSUE TITLE
Improvement on RTSP loading

### ISSUE THREAD

**Issue by warshoot3r** [rzeldent/esp32cam-rtsp#80]
Hi,
Nice work on this project. I am wondering if we can improve the RTSP connection speeds?

It takes 5 seconds but I am not sure what is causing the delay. On the other hand, the mjpeg is instantaneous. Anyone got any hints. I'm having a look at the RTSP code to try and figure it out, but appreciate if any expert got suggestions.

Cheers

**Comment by rzeldent** [comment]
Hi warshoot3r,

I believe VLC is buffering. This van be set to a shorter period.
Speeds are limited by the WiFi but here some improvement might be possible...
