### ISSUE TITLE
upoading using arduino ide

### ISSUE THREAD

**Issue by anonytech1** [rzeldent/esp32cam-rtsp#83]
would this be possible? as i do not like the UI of platform io and how to use platfor io aswell

**Comment by rzeldent** [comment]
Ho anonytech,

Sure I think this is possible. Just rename the src/main.cpp to main.ino and make sure you download the required libraries.
You might have some issues with the include files; maybe they all need to be in the same directory.
However this is as far as my support goes!

Good luck,

Rene
