### ISSUE TITLE
wifi

### ISSUE THREAD

**Issue by llaull** [rzeldent/esp32cam-rtsp#85]
hello, 
I don"t know why but i can't change the  WIFI mode access.
I try to many wifi at home 2 and 5 Ghz,

maybe i didn't see some think but i like the project so i wanted to use it :)

**Comment by llaull** [comment]
after 1day I got it !
I edited:

 // Wifi Modes
 const char *wifi_modes[] = {"STA+AP"};

thank for the project

**Comment by rzeldent** [comment]
Hi Llaill,

The ESP32 only supports 2.4GHhz. I doubt the fix is correct because this text is only for displaying the Wifi mode in the web page...
