### ISSUE TITLE
URL error & working project.

### ISSUE THREAD

**Issue by US4LKW** [rzeldent/esp32cam-rtsp#90]
Thanks for the project!
When click on the "http://192.168.4.1/flash?v=0" link, then redirect to the wrong address.
In the browser in the address bar it is displayed like this: http://192.168.4.1/%20//192.168.4.1/flash?v=0
Displays on the page:
Requested a non-existing page

URI: /%20//192.168.4.1/flash

I also had problems with the latest firmware (firmware.bin) and the latest project (esp32cam-rtsp-1.0.5).
When I flashed the latest firmware (firmware.bin), the esp32-cam did not work and go to bootloop.
The new project (esp32cam-rtsp-1.0.5) compiled and loaded into esp32-cam without errors, but did not work, the new Wi-Fi network "ESP32CAM-RTSP" did not work.
Then I took this project: https://github.com/rzeldent/esp32cam-rtsp/archive/refs/heads/develop.zip and it worked for me!

Best regards!

**Comment by rzeldent** [comment]
Hi US4LKW,

Thanks for noticing! Yes, you're right, there was a space in the URL. Made a bugfix for that!

PR: https://github.com/rzeldent/esp32cam-rtsp/pull/94
