### ISSUE TITLE
Switches for camera options 

### ISSUE THREAD

**Issue by Andreasav** [rzeldent/esp32cam-rtsp#91]
Hi 

I use your code and it works good (but I have a few seconds delay) 

So
Is it possible to add your code in esphome/in Home Assistant ? If so, how ?😊

Second 
Can I get switches (entries) in Home Assistant for camera options, ex for brightness, white balance, (flash) LED etc. 

Thank you

**Comment by rzeldent** [comment]
Hi Andreas,

I believe there is already a module for the ESP32 in Home Assistant.
Putting this code in HA is not hat easy!
You'll have to ask the maintainer of this module to add new functionality...
