### ISSUE TITLE
Restart 100second delay

### ISSUE THREAD

**Issue by berkutta** [rzeldent/esp32cam-rtsp#93]
Hi

Is there any reason to have a 100-second delay before performing the restart itself? Maybe it would make sense to remove it or at least reduce it to a few seconds.

https://github.com/rzeldent/esp32cam-rtsp/blob/aee7cbddd8b2ceb09f65d12ee309dca238a4904c/src/main.cpp#L198

**Comment by rzeldent** [comment]
Hi Benjamin,

This 100 millisecond delay is to make sure the html has been sent. Maybe this can be
omitted or shortened.
